### ISSUE TITLE
crashing server ...

### ISSUE THREAD

**Issue by MSandro** [nicguzzo/skyutils#1]
Hello, I use your mod for my new Skyblock Modpack, but it is not server compatible ... :( there is no crash log but here are the last lines of my latest.log:
```
[22:17:38] [main/INFO]: SkyblockNetherChunkGenerator
[22:17:38] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
[22:17:38] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
[22:17:38] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
[22:17:38] [main/INFO]: [STDERR]: 	... 1 more
[22:17:38] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[22:17:38] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:17:38] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:17:38] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:17:38] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
[22:17:38] [main/INFO]: [STDERR]: 	... 2 more
[22:17:38] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[22:17:38] [main/INFO]: [STDERR]: 	... 7 more
[22:17:38] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[22:17:38] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:17:38] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:17:38] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:17:38] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[22:17:38] [main/INFO]: [STDERR]: 	... 9 more
[22:17:38] [main/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5317
[22:17:38] [main/INFO]: [STDERR]: 	at net.minecraft.class_5285.localvar$zjh000$injected(class_5285.java:567)
[22:17:38] [main/INFO]: [STDERR]: 	at net.minecraft.class_5285.<init>(class_5285.java)
[22:17:38] [main/INFO]: [STDERR]: 	at net.minecraft.class_5285.method_28021(class_5285.java:227)
[22:17:38] [main/INFO]: [STDERR]: 	at net.minecraft.class_3806.<init>(class_3806.java:72)
[22:17:38] [main/INFO]: [STDERR]: 	at net.minecraft.class_3806.method_16714(class_3806.java:76)
[22:17:38] [main/INFO]: [STDERR]: 	at net.minecraft.class_3807.<init>(class_3807.java:14)
[22:17:38] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:95)
[22:17:38] [main/INFO]: [STDERR]: 	... 14 more
[22:17:38] [main/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5317
[22:17:38] [main/INFO]: [STDERR]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[22:17:38] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:17:38] [main/INFO]: [STDERR]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[22:17:38] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
[22:17:38] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:17:38] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
[22:17:38] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:17:38] [main/INFO]: [STDERR]: 	... 21 more
```

**Comment by MSandro** [comment]
[SkyUtils-1.0.1-ServerVersion.zip](https://github.com/nicguzzo/skyutils/files/6657184/SkyUtils-1.0.1-ServerVersion.zip)
I have compiled the mod by my self and removed every WorldGen Mixin, now it works on servers ...

**Comment by nicguzzo** [comment]
Fixed on latest version, I split the GeneratorOptions mixin into server and client parts
