### ISSUE TITLE
Nether is broken

### ISSUE THREAD

**Issue by Kiryonn** [nicguzzo/skyutils#3]
I created a new world generated normally but when i created my first nether portal, the nether was empty. Well there was only the structures. I Recreated a new map to be sure i wasn't wrong and yes i definitivelly selected default world gen. And i did that dozens of times just to be sure.
Here is some infos you might want: 
* version : 1.17
* mods :
    * adventurez
    * architectury
    * better third person
    * cloth config
    * enchantement descriptions
    * fabric api
    * immersive portals
    * litematica
    * lithium
    * malilib
    * mod menu
    * roughly enough items
    * stackable potions
    * voidz

**Comment by nicguzzo** [comment]
I'm aware of this, but unfortunately I couldn't find a way around that problem. 1.16+ changed the way to generate chunks and no longer have direct access to check the world type, I'm currently trying to solve this.

**Comment by nicguzzo** [comment]
I think I fixed the proble, @Kiryonn would you like to help testing it?

**Comment by Kiryonn** [comment]
Of course i would like to !

**Comment by Kiryonn** [comment]
and nope. The game crash when i put the mod in the mods folder.

**Comment by Kiryonn** [comment]
```
[06:54:53] [main/FATAL]: Mixin apply failed skyutils.mixins.json:NetherMixin -> net.minecraft.class_3754: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on buildBedrock could not find any targets matching 'Lnet/minecraft/class_3754;buildBedrock(Lnet/minecraft/class_2791;II)Lnet/minecraft/class_2791;Ljava/util/Random' in net.minecraft.class_3754. Using refmap SkyUtils-refmap.json [PREINJECT Applicator Phase -> skyutils.mixins.json:NetherMixin -> Prepare Injections ->  -> handler$bdm000$buildBedrock(Lnet/minecraft/class_2791;Ljava/util/Random;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on buildBedrock could not find any targets matching 'Lnet/minecraft/class_3754;buildBedrock(Lnet/minecraft/class_2791;II)Lnet/minecraft/class_2791;Ljava/util/Random' in net.minecraft.class_3754. Using refmap SkyUtils-refmap.json [PREINJECT Applicator Phase -> skyutils.mixins.json:NetherMixin -> Prepare Injections ->  -> handler$bdm000$buildBedrock(Lnet/minecraft/class_2791;Ljava/util/Random;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at jdk.internal.reflect.GeneratedConstructorAccessor58.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.class_5843$class_5845.<clinit>(class_5843.java:69) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_5843.<clinit>(class_5843.java:11) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_6122.<clinit>(class_6122.java:12) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:13) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:34) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:20) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:45) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:266) [intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:44) [intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:139) [intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]

```

**Comment by nicguzzo** [comment]
ups, I screwd up the buildBedrock method in the mixin. I'm working on geodes too...

**Comment by Kiryonn** [comment]
NICEUUU

**Comment by Kiryonn** [comment]
ok i tested and it seems the nether bug is not here and I don't crash either anymore. Good job ! :)
